### ISSUE TITLE
Frontend Developement

### ISSUE THREAD

**Issue by Prachit99** [ashishjoshi2605/ncsu-campus-jobs-review-system#4]
Two different webpages are required here:
1. Dashboard showing information of all the reviews
2. Additional Functionality for Admin to add new reviews into the System

**Comment by karan-47** [comment]
Home page, review page as well as review form html pages changes have been done. A few changes are yet to be pushed. 
We are working on it. Will push the changes and close the issue once done

**Comment by sankettangade** [comment]
The nav bar part is yet to be fixed. I guess @Darkspur is working on it

**Comment by Darkspur** [comment]
The navbar has been fixed
