### ISSUE TITLE
Database Modelling

### ISSUE THREAD

**Issue by Prachit99** [ashishjoshi2605/ncsu-campus-jobs-review-system#5]
As this is a review system, we need to create a model for storing various kinds of information about the reviews such as
- Store Name
- Job Type/Description
- Reviews about that specific job
- Average rating

Creation of such data model is essential before going ahead with any backend functionalities.

**Comment by sankettangade** [comment]
As discussed during our meet,can you please add a new attribute in the database for the recommendation rating in a range of 1 to 10

**Comment by karan-47** [comment]
Added the recommendation field as per the requirement
